# Generated by Django 5.2.3 on 2025-06-26 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
        ('users', '0004_auto_20250617_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='created_at',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='season',
            name='updated_at',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='season',
            name='updated_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
