# Generated by Django 5.2.3 on 2025-06-26 08:58

from django.db import migrations
from uuid import uuid4
from datetime import datetime

def insert_season(apps, schema_editor):
    user_model = apps.get_model("users", "User")
    user = user_model.objects.get(firebase_uid="fYkoyRedffYwDOyzdny4sC5zKDV2")
    my_model = apps.get_model("season", "Season")
    my_model.objects.create(id=uuid4(), name="2025", created_at=datetime.now(), updated_at=datetime.now(), updated_by=user)

class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_season_created_at_season_updated_at_and_more'),
    ]

    operations = [
        migrations.RunPython(insert_season)
    ]
