# Generated by Django 5.2.3 on 2025-07-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0003_auto_20250626_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='updated_by',
        ),
    ]
