# Generated by Django 5.2.3 on 2025-06-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sport_id', models.UUIDField(primary_key=True, serialize=False)),
                ('sport_name', models.CharField(max_length=128, unique=True)),
                ('sport_description', models.TextField()),
            ],
        ),
    ]
