# Generated by Django 5.2.3 on 2025-06-23 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='sport_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='sport_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='sport_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='sport',
            name='sport_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sport.sporttype'),
            preserve_default=False,
        ),
    ]
