# Generated by Django 5.2.3 on 2025-06-23 08:11

from django.db import migrations
from uuid import uuid4

def insert_sport_type(apps, schema_editor):
    myModel = apps.get_model('sport', 'SportType')
    myModel.objects.create(id=uuid4(), name='On Ground')
    myModel.objects.create(id=uuid4(), name='Online')


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_sporttype_rename_sport_description_sport_description_and_more'),
    ]

    operations = [
        migrations.RunPython(insert_sport_type)
    ]
