# Generated by Django 5.2.3 on 2025-06-23 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_auto_20250623_0811'),
        ('sport_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_type.sporttype'),
        ),
        migrations.DeleteModel(
            name='SportType',
        ),
    ]
