# Generated by Django 5.2.3 on 2025-07-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_alter_sport_sport_type_delete_sporttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='cover_image',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
