# Generated by Django 5.2.3 on 2025-08-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_sport_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='status',
            field=models.CharField(choices=[('NA', 'Na'), ('ACTIVE', 'Active'), ('DELETED', 'Deleted'), ('DRAFT', 'Draft')], default='ACTIVE', max_length=20),
        ),
    ]
