# Generated by Django 5.2.3 on 2025-07-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('users', '0005_user_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('team', models.ManyToManyField(related_name='member_invites', to='team.team')),
                ('user', models.ManyToManyField(related_name='invites', to='users.user')),
            ],
        ),
    ]
