# Generated by Django 5.2.3 on 2025-07-29 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_invite'),
        ('users', '0005_user_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='user',
        ),
        migrations.AddField(
            model_name='invite',
            name='invitee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to='users.user'),
        ),
        migrations.AddField(
            model_name='invite',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='users.user'),
        ),
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.RemoveField(
            model_name='invite',
            name='team',
        ),
        migrations.AddField(
            model_name='invite',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
