# Generated by Django 5.2.3 on 2025-07-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_invite_user_invite_invitee_invite_inviter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('NA', 'Na'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
