# Generated by Django 5.2.3 on 2025-07-31 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_invite_status_team_is_registered'),
        ('tournament', '0011_tournament_team_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='tournament',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.tournament'),
        ),
    ]
