# Generated by Django 5.2.3 on 2025-08-23 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_invite_tournament'),
        ('tournament', '0013_tournament_activity'),
        ('users', '0010_auto_20250812_1937'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('team', 'inviter', 'invitee', 'tournament')},
        ),
    ]
