# Generated by Django 5.2.3 on 2025-09-05 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0006_alter_invite_unique_together"),
        ("users", "0010_auto_20250812_1937"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="created_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.user"
            ),
        ),
    ]
