# Generated by Django 5.2.3 on 2025-06-25 11:54

from django.db import migrations
from uuid import uuid4

def insert_tournament_types(apps, schema_editor):
    my_model = apps.get_model("tournament", "TournamentType")
    my_model.objects.create(id=uuid4(), name='Online Individual')
    my_model.objects.create(id=uuid4(), name='Online Team')
    my_model.objects.create(id=uuid4(), name='On Ground Individual')
    my_model.objects.create(id=uuid4(), name='On Ground Team')

class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_tournament_types)
    ]
