# Generated by Django 5.2.3 on 2025-06-26 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20250625_0943'),
        ('season', '0003_auto_20250626_0858'),
        ('sport', '0004_alter_sport_sport_type_delete_sporttype'),
        ('tournament', '0002_auto_20250625_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('registration_start_date', models.DateField()),
                ('registration_end_date', models.DateField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cities', models.ManyToManyField(related_name='cities', to='city.city')),
                ('season', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='season.season')),
                ('sport', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sport.sport')),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournamenttype')),
            ],
        ),
    ]
