# Generated by Django 5.2.3 on 2025-06-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_alter_sport_sport_type_delete_sporttype'),
        ('tournament', '0003_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='sport',
        ),
        migrations.AddField(
            model_name='tournament',
            name='sport',
            field=models.ManyToManyField(default=None, related_name='sports', to='sport.sport'),
        ),
    ]
