# Generated by Django 5.2.3 on 2025-06-27 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_alter_sport_sport_type_delete_sporttype'),
        ('tournament', '0004_remove_tournament_sport_tournament_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='sport',
        ),
        migrations.AddField(
            model_name='tournament',
            name='sport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='sport.sport'),
        ),
    ]
