# Generated by Django 5.2.3 on 2025-07-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_remove_tournament_sport_tournament_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registration_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
