# Generated by Django 5.2.3 on 2025-07-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_alter_tournament_registration_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='schedule',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
