# Generated by Django 5.2.3 on 2025-07-29 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20250625_0943'),
        ('tournament', '0007_tournament_schedule'),
        ('users', '0007_remove_user_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='user',
            field=models.ManyToManyField(related_name='tournament_user', to='users.user'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='cities',
            field=models.ManyToManyField(db_index=True, related_name='cities', to='city.city'),
        ),
        migrations.CreateModel(
            name='OnlineIndividualData',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
