# Generated by Django 5.2.3 on 2025-07-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_tournament_user_alter_tournament_cities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineindividualdata',
            name='data',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='onlineindividualdata',
            name='entry_date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
