# Generated by Django 5.2.3 on 2025-07-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_alter_onlineindividualdata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='team_size',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
