# Generated by Django 5.2.3 on 2025-08-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_tournament_team_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('NA', 'Na'), ('ACTIVE', 'Active'), ('DELETED', 'Deleted'), ('DRAFT', 'Draft')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
