# Generated by Django 5.2.3 on 2025-08-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0012_tournament_created_at_tournament_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="strava_club_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
