# Generated by Django 5.2.3 on 2025-08-21 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('tournament', '0012_tournament_created_at_tournament_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_activity', to='activity.activityconfig'),
        ),
    ]
