# Generated by Django 5.2.3 on 2025-08-19 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0004_stravaclub'),
        ('tournament', '0012_tournament_created_at_tournament_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='club',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strava.stravaclub'),
        ),
    ]
