# Generated by Django 5.2.3 on 2025-09-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_tournament_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamenttype',
            name='rules',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
