# Generated by Django 5.2.3 on 2025-08-20 06:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0013_tournament_club"),
        ("users", "0011_user_strava_athlete_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("strava_activity_id", models.BigIntegerField(unique=True)),
                ("distance", models.FloatField(default=0)),
                ("moving_time", models.IntegerField()),
                ("elapsed_time", models.IntegerField()),
                ("start_date", models.DateTimeField()),
                ("sport_type", models.CharField(max_length=50)),
                ("name", models.CharField(default=None, max_length=255)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
