# Generated by Django 5.2.3 on 2025-09-05 11:55

from django.db import migrations
from uuid import uuid4

def insert_tournament_types(apps, schema_editor):
    my_model = apps.get_model("tournament", "TournamentType")
    rules = [
        {
            "label": "1+1",
            "max_guests": 1,
            "total_members": 2,
            "description": "Employee + Spouse"
        },
        {
            "label": "1+3",
            "max_guests": 3,
            "total_members": 4,
            "description": "Employee + Spouse + Parent"
        },
        {
            "label": "1+4",
            "max_guests": 4,
            "total_members": 5,
            "description": "Employee + Spouse + Parent + Child"
        }
    ]
    my_model.objects.create(id=uuid4(), name='Online Team External', rules=rules)

class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_tournamenttype_rules'),
    ]

    operations = [
        migrations.RunPython(insert_tournament_types)
    ]
