# Generated by Django 5.2.3 on 2025-08-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0014_tournamentactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
