# Generated by Django 5.2.3 on 2025-09-06 16:39

from django.db import migrations
import uuid

def add_quiz_tournament_type(apps, schema_editor):
    TournamentType = apps.get_model('tournament', 'TournamentType')
    TournamentType.objects.create(id=uuid.uuid4(), name='Quiz')

def remove_quiz_tournament_type(apps, schema_editor):
    TournamentType = apps.get_model('tournament', 'TournamentType')
    TournamentType.objects.filter(name='Quiz').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_auto_20250905_1155'),
    ]

    operations = [
        migrations.RunPython(add_quiz_tournament_type, remove_quiz_tournament_type),
    ]