# Generated by Django 5.2.3 on 2025-08-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0015_tournament_last_synced_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentactivity",
            name="strava_activity_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentactivity",
            unique_together={("tournament", "strava_activity_id")},
        ),
    ]
