# Generated by Django 5.2.3 on 2025-09-18 18:08

from django.db import migrations
from uuid import uuid4

def insert_tournament_types(apps, schema_editor):
    my_model = apps.get_model("tournament", "TournamentType")
    rules_one_plus_one = [
        {
            "label": "1+1",
            "max_guests": 1,
            "total_members": 2,
            "description": "Employee + Spouse"
        }
    ]
    rules_one_plus_three = [
        {
            "label": "1+3",
            "max_guests": 3,
            "total_members": 4,
            "description": "Employee + Spouse + Parent"
        }
    ]
    rules_one_plus_four = [
        {
            "label": "1+4",
            "max_guests": 4,
            "total_members": 5,
            "description": "Employee + Spouse + Parent + Child"
        }
    ]
    my_model.objects.create(id=uuid4(), name='Online Team External (1+1)', rules=rules_one_plus_one)
    my_model.objects.create(id=uuid4(), name='Online Team External (1+3)', rules=rules_one_plus_three)
    my_model.objects.create(id=uuid4(), name='Online Team External (1+4)', rules=rules_one_plus_four)


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_add_quiz_tournament_type'),
    ]

    operations = [
        migrations.RunPython(insert_tournament_types)
    ]
