# Generated by Django 5.2.3 on 2025-08-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metric', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
