# Generated by Django 5.2.3 on 2025-06-16 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('firebase_uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(max_length=80)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('role', models.JSONField(default=list, help_text='List of roles assigned to the user')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
