# Generated by Django 5.2.3 on 2025-06-16 15:13

from django.db import migrations

def insert_data(apps, schema_editor):
    myModel = apps.get_model("users", "User")
    myModel.objects.create(firebase_uid="ZNFAtVDt6XeCIHWfWtcDgFhb3dr2", username="Dhanvi", email="dhnvdesai@gmail.com", role=['ADMIN'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]