# Generated by Django 5.2.3 on 2025-06-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250616_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_code',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
