# Generated by Django 5.2.3 on 2025-06-17 11:52

from django.db import migrations

def insert_admin(apps, schema_editor):
    myModel = apps.get_model("users", "User")
    myModel.objects.create(firebase_uid="fYkoyRedffYwDOyzdny4sC5zKDV2", username="Admin", email="admin@dev.swedishchampionship.com", role=['ADMIN'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_employee_code'),
    ]

    operations = [
        migrations.RunPython(insert_admin)
    ]
