# Generated by Django 5.2.3 on 2025-07-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_alter_tournament_registration_end_date_and_more'),
        ('users', '0004_auto_20250617_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tournament',
            field=models.ManyToManyField(related_name='tournament_user', to='tournament.tournament'),
        ),
    ]
