# Generated by Django 5.2.3 on 2025-07-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tournament',
        ),
    ]
