# Generated by Django 5.2.3 on 2025-08-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('NA', 'Na'), ('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='NA', max_length=20),
        ),
    ]
