# Generated by Django 5.2.3 on 2025-08-12 19:37

from django.db import migrations

def insert_data(apps, schema_editor):
    myModel = apps.get_model("users", "GenderTypes")
    myModel.objects.create(name="Male")
    myModel.objects.create(name="Female")
    myModel.objects.create(name="Others")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_gendertypes_user_gender_type'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
