# Generated by Django 5.2.3 on 2025-08-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20250812_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='strava_athlete_id',
            field=models.TextField(default=None, null=True),
        ),
    ]
