# Generated by Django 5.2.3 on 2025-08-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravauser',
            name='strava_user_id',
            field=models.TextField(unique=True),
        ),
    ]
