# Generated by Django 5.2.3 on 2025-08-13 18:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0002_alter_stravauser_strava_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('sport_type', models.CharField(max_length=20)),
                ('details', models.JSONField()),
            ],
        ),
    ]
