# Generated by Django 5.2.3 on 2025-08-19 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0003_stravaactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaClub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('club_id', models.TextField()),
                ('club_link', models.URLField()),
            ],
        ),
    ]
