# Generated by Django 5.2.3 on 2025-08-17 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strava", "0003_stravaactivity"),
        ("tournament", "0013_tournament_strava_club_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="stravaactivity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="stravaactivity",
            name="strava_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="strava.stravauser",
            ),
        ),
        migrations.AddField(
            model_name="stravaactivity",
            name="tournament",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.tournament",
            ),
        ),
        migrations.AddField(
            model_name="stravaactivity",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name="StravaSync",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_sync", models.DateTimeField()),
                (
                    "tournament",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.tournament",
                    ),
                ),
            ],
        ),
    ]
