# Generated by Django 5.2.3 on 2025-08-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0004_stravaclub'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaclub',
            name='club_name',
            field=models.TextField(default=''),
        ),
    ]
