# Generated by Django 5.2.3 on 2025-08-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strava", "0005_stravaclub_club_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="stravaactivity",
            name="strava_activity_id",
            field=models.BigIntegerField(default=None, unique=True),
        ),
    ]
