# Generated by Django 5.2.3 on 2025-08-17 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0002_company_status"),
        ("tournament", "0013_tournament_strava_club_id"),
        ("users", "0010_auto_20250812_1937"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardSync",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_processed_activity", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CompanyLeaderboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_distance", models.FloatField(default=0)),
                ("total_moving_time", models.FloatField(default=0)),
                ("total_elevation_gain", models.FloatField(default=0)),
                ("activity_count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.tournament",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "tournament")},
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_distance", models.FloatField(default=0)),
                ("total_moving_time", models.FloatField(default=0)),
                ("total_elevation_gain", models.FloatField(default=0)),
                ("activity_count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "tournament")},
            },
        ),
    ]
