# Generated by Django 5.2.3 on 2025-09-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_publishedleaderboard_publishedteamleaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='total_score',
            field=models.BigIntegerField(default=0),
        ),
    ]
