# Generated by Django 5.2.3 on 2025-09-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_leaderboard_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamleaderboard',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamleaderboard',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamleaderboard',
            name='total_score',
            field=models.BigIntegerField(default=0),
        ),
    ]
