# Generated by Django 5.2.3 on 2025-08-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metric', '0002_metricconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metrics', models.ManyToManyField(related_name='metrics', to='metric.metricconfig')),
            ],
        ),
    ]
