# Generated by Django 5.2.3 on 2025-08-21 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('metric', '0002_metricconfig'),
        ('users', '0010_auto_20250812_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_data', to='activity.activityconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_data', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BigIntegerField()),
                ('activity_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_data', to='activity.activitydata')),
                ('metric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_metrics', to='metric.metricconfig')),
            ],
            options={
                'unique_together': {('activity_data', 'metric')},
            },
        ),
    ]
