# Generated by Django 5.2.3 on 2025-09-03 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activitydata_activitymetric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitydata',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='activitydata',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='activitydata',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitydata',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
