# Generated by Django 5.2.3 on 2025-09-04 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_remove_activitydata_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymetric',
            name='activity_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='activity.activitydata'),
        ),
    ]
