# Generated by Django 5.2.3 on 2025-09-04 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activitymetric_activity_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydata',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
