# Generated by Django 5.2.3 on 2025-09-08 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_activitydata_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydata',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='activitydata',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
