# Generated by Django 5.2.3 on 2025-09-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_activitydata_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitydata',
            old_name='end_date',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='activitydata',
            old_name='start_date',
            new_name='start_datetime',
        ),
    ]
