# Generated by Django 5.2.3 on 2025-08-11 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('season', '0004_remove_season_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='season.season'),
        ),
    ]
