# Generated by Django 5.2.3 on 2025-08-16 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("icon", "0001_initial"),
        ("news", "0002_news_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="icon.icon",
            ),
        ),
    ]
