# Generated by Django 5.2.3 on 2025-06-25 09:43

from django.db import migrations
from uuid import uuid4

def insert_cities(apps, schema_editor):
    my_model = apps.get_model("city", "City")
    my_model.objects.create(id=uuid4(), name="Bengaluru", state="Karnataka")
    my_model.objects.create(id=uuid4(), name="Pune", state="Maharashtra")
    my_model.objects.create(id=uuid4(), name="New Delhi", state="Delhi")


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_cities)
    ]
