# Generated by Django 5.2.3 on 2025-06-15 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventPlace',
            fields=[
                ('event_place_id', models.UUIDField(primary_key=True, serialize=False)),
                ('event_place_name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('event_type_id', models.UUIDField(primary_key=True, serialize=False)),
                ('event_type_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=256, unique=True)),
                ('event_venue', models.JSONField(default=list)),
                ('event_start_date', models.DateField(help_text='Start date of event')),
                ('event_end_date', models.DateField(help_text='End date of event')),
                ('event_registration_start_date', models.DateField(help_text='Users can register to events starting from this date')),
                ('event_registration_end_date', models.DateField(help_text='Users have to register to events before this date')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventtype')),
            ],
        ),
    ]
