# Generated by Django 5.2.3 on 2025-06-15 10:57

from django.db import migrations
from uuid import uuid4

def insert_event_types(apps, schema_editor):
    myModel = apps.get_model("events", "EventType")
    myModel.objects.create(event_type_id=uuid4(), event_type_name="On Ground")
    myModel.objects.create(event_type_id=uuid4(), event_type_name="Online")

def insert_event_places(apps, schema_editor):
    myModel = apps.get_model("events", "EventPlace")
    myModel.objects.create(event_place_id=uuid4(), event_place_name="Bengaluru")
    myModel.objects.create(event_place_id=uuid4(), event_place_name="Hyderabad")
    myModel.objects.create(event_place_id=uuid4(), event_place_name="Pune")
    myModel.objects.create(event_place_id=uuid4(), event_place_name="Mumbai")


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_event_types),
        migrations.RunPython(insert_event_places),
    ]
