# Generated by Django 5.2.3 on 2025-06-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20250615_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_venue',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
