# Generated by Django 5.2.3 on 2025-09-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_questionpool_question_pool_quizround_question_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizround',
            name='duration',
            field=models.IntegerField(default=2, help_text='Duration in minutes'),
        ),
    ]
